### ISSUE TITLE
SolrCloud with Microsoft Dependency Injection

### ISSUE THREAD

**Issue by Wintermute79** [SolrNet/SolrNet#582] opened 2022-02-16 01:52 UTC
Is it possible to use SolrNet Cloud with ASP.NET Core built-in dependency injection?
There is no integration or example like for Unity or autofac, has anyone done this, yet?

**Comment by mausch** [comment] 2022-02-17 20:30
There's no project for this at the moment. PRs welcome :slightly_smiling_face:

**Comment by mausch** [comment] 2022-02-17 20:41
Duplicate of https://github.com/SolrNet/SolrNet/issues/381

**Closed by mausch** 2022-02-17 20:41 UTC

**Comment by Wintermute79** [comment] 2022-02-24 17:45
> There's no project for this at the moment. PRs welcome 🙂

Done in #585  🙂
